Laboratorium 2/Models/Birth.cs
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Xml.Linq;

namespace Laboratorium_2.Models
{
    public class Birth { 
    public string? Name { get; set; }
    public DateTime Date { get; set; }
    public bool IsValid()
    {
        return Name != null && DateTime.Today.Year - Date.Year >= 0;
    }
    public int BirthDate()
    {

        var today = DateTime.Today;
        int age = today.Year - Date.Year;
        return age;
    }
}
}

Laboratorium 2/Models/Calculator.cs
namespace Laboratorium_2.Models
{
    public class Calculator
    {
        public double? A { get; set; }
        public double? B { get; set; }
        public Operators? Op { get; set; }

        public bool IsValid()
        {
            return A != null && B != null && Op != null;
        }

        public double Calculate()
        {
            switch (Op)
            {
                case Operators.ADD:
                    return (double)(A + B);
                case Operators.SUB:
                    return (double)(A - B);
                case Operators.MUL:
                    return (double)(A * B);
                case Operators.DIV:
                    return (double)(A / B);
                default: return double.NaN;
            }
        }

        public string Sign()
        {
            switch (Op)
            {
                case Operators.ADD:
                    return "+";
                case Operators.SUB:
                    return "-";
                case Operators.MUL:
                    return "*";
                case Operators.DIV:
                    return "/";
                default: return "";
            }
        }
    }
}

Laboratorium 2/Models/ErrorViewModel.cs
namespace Laboratorium_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 2/Models/Operators.cs
namespace Laboratorium_2.Models
{
    public enum Operators
    {
        ADD, SUB, MUL, DIV, POW
    }
}

Laboratorium 2/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium_2.Models;

namespace Laboratorium_2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        public IActionResult Result(Birth model)
        {
            if (!model.IsValid()) return BadRequest();

            return View(model);
        }
    }
}

Laboratorium 2/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result([FromForm]Models.Calculator model)
        {
            if (!model.IsValid()) return BadRequest();

            return View(model);
        }
    }
}

Laboratorium 2/Controllers/HomeController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium 2/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form action="Result" method="get">
    <input placeholder="Your name" type="text" name="name" />
    <label>Birth date:</label>
    <input type="date" name="date" />
    <button type="submit">Calculate</button>
</form>

Laboratorium 2/Views/Birth/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main>
    <h2>Hi @Model.Name, you have @Model.BirthDate() years</h2>
</main>

Laboratorium 2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Calculator</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="a">Number 1</label>
                    <input class="form-control" type="number" name="a" step="0.00001" id="a" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select name="op">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="b">Number 2</label>
                    <input class="form-control" type="number" name="b" step="0.00001" id="b" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

Laboratorium 2/Views/Calculator/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main>
    <h2>@Model.A @Model.Sign() @Model.B = @Model.Calculate()</h2>
</main>

Laboratorium 2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Laboratorium 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="form">Calulator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="form">Birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>